import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { Octokit } from "@octokit/rest";

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.accessToken) {
      return NextResponse.json({ error: "not authenticated" }, { status: 401 });
    }

    const body = await req.json();
    const { owner, repo, filePath, finding, policyId, suggestedFix } = body;
    const token = session.accessToken;

    const octokit = new Octokit({ auth: token });
    const cweId = finding.cwe || "CWE-Unknown";
    const branchName = `code-guardian/fix-${policyId?.toLowerCase() || "pol"}-${Date.now()}`;

    // 1. Get default branch SHA
    const { data: repoData } = await octokit.repos.get({ owner, repo });
    const defaultBranch = repoData.default_branch;

    const { data: baseRef } = await octokit.git.getRef({
      owner, repo,
      ref: `heads/${defaultBranch}`,
    });
    const baseSha = baseRef.object.sha;

    // 2. Create new branch
    await octokit.git.createRef({
      owner, repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    // 3. Get current file content
    const { data: fileData } = await octokit.repos.getContent({
      owner, repo,
      path: filePath,
      ref: defaultBranch,
    }) as { data: { content: string; sha: string; encoding: string } };

    // 4. Apply fix
    const currentContent = Buffer.from(
      fileData.content, 'base64'
    ).toString('utf8');

    const lines = currentContent.split('\n');
    const fixComment = suggestedFix || `# TODO: Fix ${cweId} security issue here`;
    lines.splice(finding.line - 1, 0, `# [Code Guardian Fix - ${policyId}]: ${fixComment}`);
    const updatedContent = lines.join('\n');

    // 5. Commit the fix
    await octokit.repos.createOrUpdateFileContents({
      owner, repo,
      path: filePath,
      message: `fix(security): ${finding.title} [${policyId}] [${cweId}]`,
      content: Buffer.from(updatedContent).toString('base64'),
      branch: branchName,
      sha: fileData.sha,
    });

    // 6. Open the PR
    const { data: pr } = await octokit.pulls.create({
      owner, repo,
      title: `[Code Guardian] ${finding.severity.toUpperCase()}: ${finding.title} (${cweId})`,
      body: [
        `## 🛡️ Security Fix by Code Guardian`,
        ``,
        `**Finding:** ${finding.title}`,
        `**File:** \`${filePath}\` · Line ${finding.line}`,
        `**Severity:** ${finding.severity.toUpperCase()}`,
        `**CWE:** ${cweId}`,
        `**Policy:** ${policyId}`,
        ``,
        `## Suggested Fix`,
        `\`\`\``,
        suggestedFix || '# See inline comment in file',
        `\`\`\``,
        ``,
        `---`,
        `*Auto-generated by Code Guardian*`,
      ].join('\n'),
      head: branchName,
      base: defaultBranch,
      draft: false,
    });

    try {
      await octokit.issues.addLabels({
        owner, repo,
        issue_number: pr.number,
        labels: ['security', 'code-guardian'],
      });
    } catch (_) { /* label may not exist, non-critical */ }

    return NextResponse.json({ 
      prNumber: pr.number, 
      prUrl: pr.html_url,
      branchName 
    });

  } catch (error: any) {
    console.error('PR creation failed:', error);
    const message = error?.response?.data?.message || error?.message || 'PR creation failed';
    const status = error?.status || 500;
    return NextResponse.json({ error: message }, { status });
  }
}
